# Generated by Django 6.0.7 on 2026-07-09 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('age', models.IntegerField()),
                ('role', models.CharField(choices=[('software_engineer', 'Software Engineer'), ('junior_software_engineer', 'Junior Software Engineer'), ('senior_software_engineer', 'Senior Software Engineer'), ('lead_engineer', 'Lead Engineer')], default='junior_software_engineer', max_length=50)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('join_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
